<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LineageSpriteStudio</AssemblyName>
    <RootNamespace>LineageSpriteStudio</RootNamespace>
    <Version>2.3.4</Version>
    <FileVersion>2.3.4.0</FileVersion>
    <AssemblyVersion>2.3.4.0</AssemblyVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
  </ItemGroup>
</Project>
